# **Referências citadas**

1. WDF Architecture \- Developing Drivers with the Windows® Driver Foundation \[Book\], acessado em novembro 1, 2025, [https://www.oreilly.com/library/view/developing-drivers-with/9780735623743/ch04s04.html](https://www.oreilly.com/library/view/developing-drivers-with/9780735623743/ch04s04.html)  
2. Architecture of the Kernel-Mode Driver Framework \- CS@Purdue, acessado em novembro 1, 2025, [https://www.cs.purdue.edu/homes/apm/courses/CS490M-fall06/project-descriptions/Microsoft/driver-docs/KMDF-arch-2.doc](https://www.cs.purdue.edu/homes/apm/courses/CS490M-fall06/project-descriptions/Microsoft/driver-docs/KMDF-arch-2.doc)  
3. Comparing UMDF 2 Functionality to KMDF \- Windows drivers ..., acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/comparing-umdf-2-0-functionality-to-kmdf](https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/comparing-umdf-2-0-functionality-to-kmdf)  
4. Understanding the Windows I/O System | Microsoft Press Store, acessado em novembro 1, 2025, [https://www.microsoftpressstore.com/articles/article.aspx?p=2201309\&seqNum=4](https://www.microsoftpressstore.com/articles/article.aspx?p=2201309&seqNum=4)  
5. WDF and WDM \- Developing Drivers with the Windows® Driver Foundation \[Book\] \- O'Reilly, acessado em novembro 1, 2025, [https://www.oreilly.com/library/view/developing-drivers-with/9780735623743/ch03s01.html](https://www.oreilly.com/library/view/developing-drivers-with/9780735623743/ch03s01.html)  
6. Communication between kernel-mode and user-mode application \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/4939030/communication-between-kernel-mode-and-user-mode-application](https://stackoverflow.com/questions/4939030/communication-between-kernel-mode-and-user-mode-application)  
7. NULL dereference \- Why does it work? \- Information Security Stack Exchange, acessado em novembro 1, 2025, [https://security.stackexchange.com/questions/270612/null-dereference-why-does-it-work](https://security.stackexchange.com/questions/270612/null-dereference-why-does-it-work)  
8. WDM Concepts for WDF Drivers \- Windows drivers | Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/wdm-concepts-for-kmdf-drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/wdm-concepts-for-kmdf-drivers)  
9. Cdev structure and File Operations of Character drivers \- Driver 6, acessado em novembro 1, 2025, [https://embetronicx.com/tutorials/linux/device-drivers/cdev-structure-and-file-operations-of-character-drivers/](https://embetronicx.com/tutorials/linux/device-drivers/cdev-structure-and-file-operations-of-character-drivers/)  
10. Block Device Drivers — The Linux Kernel documentation, acessado em novembro 1, 2025, [https://linux-kernel-labs.github.io/refs/heads/master/labs/block\_device\_drivers.html](https://linux-kernel-labs.github.io/refs/heads/master/labs/block_device_drivers.html)  
11. Network Device Driver \- Sungju's Pages, acessado em novembro 1, 2025, [https://sungju.github.io/kernel/internals/network\_driver/](https://sungju.github.io/kernel/internals/network_driver/)  
12. What is the difference between a WDM driver, a KMDF driver and a UMDF driver?, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/16569526/what-is-the-difference-between-a-wdm-driver-a-kmdf-driver-and-a-umdf-driver](https://stackoverflow.com/questions/16569526/what-is-the-difference-between-a-wdm-driver-a-kmdf-driver-and-a-umdf-driver)  
13. Windows Driver Frameworks \- Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/](https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/)  
14. Differences Between WDM and WDF \- Windows drivers | Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/differences-between-wdm-and-kmdf](https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/differences-between-wdm-and-kmdf)  
15. Blue screen of death \- Wikipedia, acessado em novembro 1, 2025, [https://en.wikipedia.org/wiki/Blue\_screen\_of\_death](https://en.wikipedia.org/wiki/Blue_screen_of_death)  
16. The NT Insider:UMDF 101 \- Understanding User Mode Driver Frameworks \- OSR Online, acessado em novembro 1, 2025, [https://www.osronline.com/article.cfm%5Eid=449.htm](https://www.osronline.com/article.cfm%5Eid=449.htm)  
17. Testing a WDF Driver (KMDF or UMDF) \- Windows \- Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/testing-a-kmdf-driver](https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/testing-a-kmdf-driver)  
18. WdfRequestGetIoQueue function (wdfrequest.h) \- Windows drivers \- Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfrequest/nf-wdfrequest-wdfrequestgetioqueue](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfrequest/nf-wdfrequest-wdfrequestgetioqueue)  
19. WDF Architecture \- Windows drivers | Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/kernel-mode-driver-framework-architecture](https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/kernel-mode-driver-framework-architecture)  
20. WDF for Genesis, acessado em novembro 1, 2025, [https://www.i.u-tokyo.ac.jp/edu/training/ss/msprojects/data/03-WindowsDriverFoundation.pdf](https://www.i.u-tokyo.ac.jp/edu/training/ss/msprojects/data/03-WindowsDriverFoundation.pdf)  
21. Custom software driver communication with user client on Windows \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/66314750/custom-software-driver-communication-with-user-client-on-windows](https://stackoverflow.com/questions/66314750/custom-software-driver-communication-with-user-client-on-windows)  
22. What is a Hardware Abstraction Layer and How Does it Work? \- Lenovo, acessado em novembro 1, 2025, [https://www.lenovo.com/us/en/glossary/hardware-abstraction-layer/](https://www.lenovo.com/us/en/glossary/hardware-abstraction-layer/)  
23. Windows Kernel-Mode HAL Library \- Windows drivers | Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/sk-sk/windows-hardware/drivers/kernel/windows-kernel-mode-hal-library](https://learn.microsoft.com/sk-sk/windows-hardware/drivers/kernel/windows-kernel-mode-hal-library)  
24. Windows Kernel-Mode HAL Library \- Windows drivers | Microsoft ..., acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/windows-kernel-mode-hal-library](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/windows-kernel-mode-hal-library)  
25. Kernel modules — The Linux Kernel documentation, acessado em novembro 1, 2025, [https://linux-kernel-labs.github.io/refs/heads/master/labs/kernel\_modules.html](https://linux-kernel-labs.github.io/refs/heads/master/labs/kernel_modules.html)  
26. Chapter 1\. Working with kernel modules | Kernel Administration Guide | Red Hat Enterprise Linux | 7, acessado em novembro 1, 2025, [https://docs.redhat.com/en/documentation/red\_hat\_enterprise\_linux/7/html/kernel\_administration\_guide/chap-documentation-kernel\_administration\_guide-working\_with\_kernel\_modules](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/7/html/kernel_administration_guide/chap-documentation-kernel_administration_guide-working_with_kernel_modules)  
27. Kernel module \- ArchWiki, acessado em novembro 1, 2025, [https://wiki.archlinux.org/title/Kernel\_module](https://wiki.archlinux.org/title/Kernel_module)  
28. Driver Basics — The Linux Kernel documentation, acessado em novembro 1, 2025, [https://www.kernel.org/doc/html/v5.1/driver-api/basics.html](https://www.kernel.org/doc/html/v5.1/driver-api/basics.html)  
29. Linux Kernel Development \- Part 1: Hello Kernel\! \- Denis Cavalli \- EmbeddedRelated.com, acessado em novembro 1, 2025, [https://www.embeddedrelated.com/showarticle/1274.php](https://www.embeddedrelated.com/showarticle/1274.php)  
30. \_\_init and \_\_exit Macros in Linux Kernel Development \- FastBitLab, acessado em novembro 1, 2025, [https://fastbitlab.com/linux-device-driver-programming-lecture-18-\_\_init-and-\_\_exit-macros/](https://fastbitlab.com/linux-device-driver-programming-lecture-18-__init-and-__exit-macros/)  
31. Hello World (part 3): The \_\_init and \_\_exit Macros \- The Linux Documentation Project, acessado em novembro 1, 2025, [https://tldp.org/LDP/lkmpg/2.4/html/x281.htm](https://tldp.org/LDP/lkmpg/2.4/html/x281.htm)  
32. Character device drivers — The Linux Kernel documentation, acessado em novembro 1, 2025, [https://linux-kernel-labs.github.io/refs/heads/master/labs/device\_drivers.html](https://linux-kernel-labs.github.io/refs/heads/master/labs/device_drivers.html)  
33. Linux Kernel: file\_operations Struct Reference \- Huihoo, acessado em novembro 1, 2025, [https://docs.huihoo.com/doxygen/linux/kernel/3.7/structfile\_\_operations.html](https://docs.huihoo.com/doxygen/linux/kernel/3.7/structfile__operations.html)  
34. Device driver — File Operations structure | by Arunkumar Krishnan \- Medium, acessado em novembro 1, 2025, [https://arunk2.medium.com/device-driver-file-operations-structure-14452edba24d](https://arunk2.medium.com/device-driver-file-operations-structure-14452edba24d)  
35. What is the difference between ioctl(), unlocked\_ioctl() and compat\_ioctl()?, acessado em novembro 1, 2025, [https://unix.stackexchange.com/questions/4711/what-is-the-difference-between-ioctl-unlocked-ioctl-and-compat-ioctl](https://unix.stackexchange.com/questions/4711/what-is-the-difference-between-ioctl-unlocked-ioctl-and-compat-ioctl)  
36. where do char device appear after cdev\_add() registers successfully with major on 117., acessado em novembro 1, 2025, [https://stackoverflow.com/questions/41320939/where-do-char-device-appear-after-cdev-add-registers-successfully-with-major-o](https://stackoverflow.com/questions/41320939/where-do-char-device-appear-after-cdev-add-registers-successfully-with-major-o)  
37. Different approaches in character device creation with a Linux kernel module, acessado em novembro 1, 2025, [https://rockyhotas.github.io/linux,/kernel,/modules,/device/2021/11/16/linux-char-devices.html](https://rockyhotas.github.io/linux,/kernel,/modules,/device/2021/11/16/linux-char-devices.html)  
38. what is difference between cdev\_alloc and cdev\_init \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/20783877/what-is-difference-between-cdev-alloc-and-cdev-init](https://stackoverflow.com/questions/20783877/what-is-difference-between-cdev-alloc-and-cdev-init)  
39. Linux block device driver \- Oleg Kutkov personal blog, acessado em novembro 1, 2025, [https://olegkutkov.me/2020/02/10/linux-block-device-driver/](https://olegkutkov.me/2020/02/10/linux-block-device-driver/)  
40. Simple block driver example \- LWN.net, acessado em novembro 1, 2025, [https://lwn.net/Articles/58720/](https://lwn.net/Articles/58720/)  
41. Linux Device Drivers, 2nd Edition: Chapter 12: Loading Block Drivers \- XML.com, acessado em novembro 1, 2025, [https://www.xml.com/ldd/chapter/book/ch12.html](https://www.xml.com/ldd/chapter/book/ch12.html)  
42. Network Devices, the Kernel, and You\!, acessado em novembro 1, 2025, [https://docs.kernel.org/networking/netdevices.html](https://docs.kernel.org/networking/netdevices.html)  
43. 6.7 About Network Device Drivers, acessado em novembro 1, 2025, [https://docs.oracle.com/en/operating-systems/oracle-linux/6/porting/ch06s07.html](https://docs.oracle.com/en/operating-systems/oracle-linux/6/porting/ch06s07.html)  
44. linux kernel \- How to write a dummy network device driver \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/42521437/how-to-write-a-dummy-network-device-driver](https://stackoverflow.com/questions/42521437/how-to-write-a-dummy-network-device-driver)  
45. Device Tree Technical Overview | Toradex Developer Center, acessado em novembro 1, 2025, [https://developer.toradex.com/software/linux-resources/device-tree/device-tree-overview/](https://developer.toradex.com/software/linux-resources/device-tree/device-tree-overview/)  
46. Devicetree \- Wikipedia, acessado em novembro 1, 2025, [https://en.wikipedia.org/wiki/Devicetree](https://en.wikipedia.org/wiki/Devicetree)  
47. ELI5: Is there any good reason why ARM systems can't use something like ACPI+UEFI to eliminate the need for device tree (DTB) files and open easier, wider OS compatibility on ARM systems? : r/hardware \- Reddit, acessado em novembro 1, 2025, [https://www.reddit.com/r/hardware/comments/ymh8uu/eli5\_is\_there\_any\_good\_reason\_why\_arm\_systems/](https://www.reddit.com/r/hardware/comments/ymh8uu/eli5_is_there_any_good_reason_why_arm_systems/)  
48. Mastering Device Trees: A Guide to Hardware Integration in Linux | by Hasan Can Sert, acessado em novembro 1, 2025, [https://medium.com/@hasancansert/mastering-device-trees-a-guide-to-hardware-integration-in-linux-3e1516a75e04](https://medium.com/@hasancansert/mastering-device-trees-a-guide-to-hardware-integration-in-linux-3e1516a75e04)  
49. Linux and the Devicetree \- The Linux Kernel documentation, acessado em novembro 1, 2025, [https://docs.kernel.org/devicetree/usage-model.html](https://docs.kernel.org/devicetree/usage-model.html)  
50. Device Tree for Dummies, acessado em novembro 1, 2025, [https://events.static.linuxfound.org/sites/events/files/slides/petazzoni-device-tree-dummies.pdf](https://events.static.linuxfound.org/sites/events/files/slides/petazzoni-device-tree-dummies.pdf)  
51. ACPI vs Device Tree | Linux kernel and Linux device driver \- YouTube, acessado em novembro 1, 2025, [https://www.youtube.com/watch?v=UIXtM1IlnG4](https://www.youtube.com/watch?v=UIXtM1IlnG4)  
52. Why do embedded systems need device tree while pcs don't?, acessado em novembro 1, 2025, [https://unix.stackexchange.com/questions/399619/why-do-embedded-systems-need-device-tree-while-pcs-dont](https://unix.stackexchange.com/questions/399619/why-do-embedded-systems-need-device-tree-while-pcs-dont)  
53. Garrett: Why ACPI? \[LWN.net\], acessado em novembro 1, 2025, [https://lwn.net/Articles/949625/](https://lwn.net/Articles/949625/)  
54. ACPI vs Device Tree \- moving forward \- Google Groups, acessado em novembro 1, 2025, [https://groups.google.com/g/linux.kernel/c/DHkvN79EF2k](https://groups.google.com/g/linux.kernel/c/DHkvN79EF2k)  
55. Why ACPI? \- mjg59, acessado em novembro 1, 2025, [https://mjg59.dreamwidth.org/68350.html?thread=2156542](https://mjg59.dreamwidth.org/68350.html?thread=2156542)  
56. linux \- Difference between dts and ACPI \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/32310935/difference-between-dts-and-acpi](https://stackoverflow.com/questions/32310935/difference-between-dts-and-acpi)  
57. SetupDiEnumDeviceInfo function (setupapi.h) \- Win32 apps \- Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdienumdeviceinfo](https://learn.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdienumdeviceinfo)  
58. Enumerate Installed Devices \- Windows drivers \- Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/install/enumerating-installed-devices](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/enumerating-installed-devices)  
59. DeviceIoControl function (ioapiset.h) \- Win32 apps \- Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows/win32/api/ioapiset/nf-ioapiset-deviceiocontrol](https://learn.microsoft.com/en-us/windows/win32/api/ioapiset/nf-ioapiset-deviceiocontrol)  
60. Calling DeviceIoControl \- Win32 apps | Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows/win32/devio/calling-deviceiocontrol](https://learn.microsoft.com/en-us/windows/win32/devio/calling-deviceiocontrol)  
61. List the USB devices connected · GitHub, acessado em novembro 1, 2025, [https://gist.github.com/9ac217aa218e32372eb4](https://gist.github.com/9ac217aa218e32372eb4)  
62. Read/write into a device in C++ \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/6525812/read-write-into-a-device-in-c](https://stackoverflow.com/questions/6525812/read-write-into-a-device-in-c)  
63. Reading a Linux device with fstream \- c++ \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/6064890/reading-a-linux-device-with-fstream](https://stackoverflow.com/questions/6064890/reading-a-linux-device-with-fstream)  
64. udev \- Wikipedia, acessado em novembro 1, 2025, [https://en.wikipedia.org/wiki/Udev](https://en.wikipedia.org/wiki/Udev)  
65. An introduction to Udev: The Linux subsystem for managing device events, acessado em novembro 1, 2025, [https://opensource.com/article/18/11/udev](https://opensource.com/article/18/11/udev)  
66. 9.3. Overview of Device and Module Handling \- Linux From Scratch\!, acessado em novembro 1, 2025, [https://www.linuxfromscratch.org/lfs/view/12.4/chapter09/udev.html](https://www.linuxfromscratch.org/lfs/view/12.4/chapter09/udev.html)  
67. 6.3 About Udev Rules, acessado em novembro 1, 2025, [https://docs.oracle.com/en/operating-systems/oracle-linux/6/admin/about-udev-rules.html](https://docs.oracle.com/en/operating-systems/oracle-linux/6/admin/about-udev-rules.html)  
68. A.3. Device Mapper Support for the udev Device Manager \- Red Hat Documentation, acessado em novembro 1, 2025, [https://docs.redhat.com/en/documentation/red\_hat\_enterprise\_linux/7/html/logical\_volume\_manager\_administration/udev\_device\_manager](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/7/html/logical_volume_manager_administration/udev_device_manager)  
69. Dynamic Kernel Device Management with udev | Administration Guide | SLES 12 SP5, acessado em novembro 1, 2025, [https://documentation.suse.com/sles/12-SP5/html/SLES-all/cha-udev.html](https://documentation.suse.com/sles/12-SP5/html/SLES-all/cha-udev.html)  
70. How to read and consume the input of /dev/input/ \- Unix & Linux Stack Exchange, acessado em novembro 1, 2025, [https://unix.stackexchange.com/questions/666478/how-to-read-and-consume-the-input-of-dev-input](https://unix.stackexchange.com/questions/666478/how-to-read-and-consume-the-input-of-dev-input)  
71. Read from /dev/input \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/15949163/read-from-dev-input](https://stackoverflow.com/questions/15949163/read-from-dev-input)  
72. Block device information without mounting in Linux \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/8416241/block-device-information-without-mounting-in-linux](https://stackoverflow.com/questions/8416241/block-device-information-without-mounting-in-linux)  
73. How to talk to device drivers? \- C++ Forum, acessado em novembro 1, 2025, [https://cplusplus.com/forum/unices/36170/](https://cplusplus.com/forum/unices/36170/)  
74. ioctl(2) \- Linux manual page \- man7.org, acessado em novembro 1, 2025, [https://man7.org/linux/man-pages/man2/ioctl.2.html](https://man7.org/linux/man-pages/man2/ioctl.2.html)  
75. Troubleshooting Windows unexpected restarts and stop code errors \- Microsoft Support, acessado em novembro 1, 2025, [https://support.microsoft.com/en-us/windows/troubleshooting-windows-unexpected-restarts-and-stop-code-errors-60b01860-58f2-be66-7516-5c45a66ae3c6](https://support.microsoft.com/en-us/windows/troubleshooting-windows-unexpected-restarts-and-stop-code-errors-60b01860-58f2-be66-7516-5c45a66ae3c6)  
76. IRQL NOT LESS OR EQUAL – Fix for Windows 10, 11, XP, Vista, 7, 8, acessado em novembro 1, 2025, [https://neosmart.net/wiki/irql-not-less-or-equal/](https://neosmart.net/wiki/irql-not-less-or-equal/)  
77. How to fix Error 0xA: IRQL\_not\_less\_or\_equal \- Microsoft Support, acessado em novembro 1, 2025, [https://support.microsoft.com/en-gb/windows/how-to-fix-error-0xa-irql-not-less-or-equal-fd19c7fc-89d2-67a5-4fb0-a1f8bd1f0202](https://support.microsoft.com/en-gb/windows/how-to-fix-error-0xa-irql-not-less-or-equal-fd19c7fc-89d2-67a5-4fb0-a1f8bd1f0202)  
78. Understanding Windows Kernel Pool Memory | White Knight Labs, acessado em novembro 1, 2025, [https://whiteknightlabs.com/2025/03/24/understanding-windows-kernel-pool-memory/](https://whiteknightlabs.com/2025/03/24/understanding-windows-kernel-pool-memory/)  
79. What are "Commited Memory", "Cached", "Paged", "Not-paged pool" & How They are Different with "In-Use Memory" \- Super User, acessado em novembro 1, 2025, [https://superuser.com/questions/1410289/what-are-commited-memory-cached-paged-not-paged-pool-how-they-are-d](https://superuser.com/questions/1410289/what-are-commited-memory-cached-paged-not-paged-pool-how-they-are-d)  
80. Paged pool memory or Nonpaged pool memory ?? (windows driver development) \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/796848/paged-pool-memory-or-nonpaged-pool-memory-windows-driver-development](https://stackoverflow.com/questions/796848/paged-pool-memory-or-nonpaged-pool-memory-windows-driver-development)  
81. Memory Pools \- Win32 apps \- Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows/win32/memory/memory-pools](https://learn.microsoft.com/en-us/windows/win32/memory/memory-pools)  
82. ELI5: Paged versus Non-Paged Memory Pools, virtual memory, etc : r/explainlikeimfive, acessado em novembro 1, 2025, [https://www.reddit.com/r/explainlikeimfive/comments/6sp69q/eli5\_paged\_versus\_nonpaged\_memory\_pools\_virtual/](https://www.reddit.com/r/explainlikeimfive/comments/6sp69q/eli5_paged_versus_nonpaged_memory_pools_virtual/)  
83. DSAC: Effective Static Analysis of Sleep-in-Atomic-Context Bugs in Kernel Modules, acessado em novembro 1, 2025, [https://www.usenix.org/conference/atc18/presentation/bai](https://www.usenix.org/conference/atc18/presentation/bai)  
84. Linux: Sleeping while atomic during kmalloc solved \- Bhanage.com, acessado em novembro 1, 2025, [https://www.bhanage.com/2019/06/linux-sleeping-while-atomic-during.html](https://www.bhanage.com/2019/06/linux-sleeping-while-atomic-during.html)  
85. linux kernel \- atomic context and process context/interrupt context \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/47063693/atomic-context-and-process-context-interrupt-context](https://stackoverflow.com/questions/47063693/atomic-context-and-process-context-interrupt-context)  
86. Atomic context and kernel API design \- LWN.net, acessado em novembro 1, 2025, [https://lwn.net/Articles/274695/](https://lwn.net/Articles/274695/)  
87. Understanding Null Pointer Dereference in Windows Kernel Drivers ..., acessado em novembro 1, 2025, [https://whiteknightlabs.com/2025/06/24/understanding-null-pointer-dereference-in-windows-kernel-drivers/](https://whiteknightlabs.com/2025/06/24/understanding-null-pointer-dereference-in-windows-kernel-drivers/)  
88. Null pointer dereference in User space and kernel space \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/35239407/null-pointer-dereference-in-user-space-and-kernel-space](https://stackoverflow.com/questions/35239407/null-pointer-dereference-in-user-space-and-kernel-space)  
89. What happens in OS when we dereference a NULL pointer in C? \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/12645647/what-happens-in-os-when-we-dereference-a-null-pointer-in-c](https://stackoverflow.com/questions/12645647/what-happens-in-os-when-we-dereference-a-null-pointer-in-c)
1. Propósito de um software de driver : r/embedded \- Reddit, acessado em novembro 1, 2025, [https://www.reddit.com/r/embedded/comments/1nxp7u4/purpose\_of\_a\_driver\_software/?tl=pt-br](https://www.reddit.com/r/embedded/comments/1nxp7u4/purpose_of_a_driver_software/?tl=pt-br)  
2. Responsabilidades do Driver de Dispositivo \- IBM, acessado em novembro 1, 2025, [https://www.ibm.com/docs/pt-br/aix/7.3.0?topic=overview-responsibilities-device-driver](https://www.ibm.com/docs/pt-br/aix/7.3.0?topic=overview-responsibilities-device-driver)  
3. Visão geral de Como desenvolver drivers de cliente Windows para dispositivos USB, acessado em novembro 1, 2025, [https://learn.microsoft.com/pt-br/windows-hardware/drivers/usbcon/usb-driver-development-guide](https://learn.microsoft.com/pt-br/windows-hardware/drivers/usbcon/usb-driver-development-guide)  
4. O que é um driver? \- Windows drivers | Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/pt-br/windows-hardware/drivers/gettingstarted/what-is-a-driver-](https://learn.microsoft.com/pt-br/windows-hardware/drivers/gettingstarted/what-is-a-driver-)  
5. Windows Kernel-Mode I/O Manager \- Windows drivers \- Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/windows-kernel-mode-i-o-manager](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/windows-kernel-mode-i-o-manager)  
6. BSOD Multiple IRP Complete Requests, usbxhci.sys \- Microsoft Q\&A, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/answers/questions/4322177/bsod-multiple-irp-complete-requests-usbxhci-sys](https://learn.microsoft.com/en-us/answers/questions/4322177/bsod-multiple-irp-complete-requests-usbxhci-sys)  
7. Polling/Interrupt/DMA differences explained easily \- YouTube, acessado em novembro 1, 2025, [https://www.youtube.com/watch?v=LNPBr3WvuNg](https://www.youtube.com/watch?v=LNPBr3WvuNg)  
8. O que são os Interrupts (e o Polling)? \- Aberto até de Madrugada, acessado em novembro 1, 2025, [https://abertoatedemadrugada.com/2012/10/o-que-sao-os-interrupts-e-o-polling.html](https://abertoatedemadrugada.com/2012/10/o-que-sao-os-interrupts-e-o-polling.html)  
9. Interrupções assíncronas e síncronas \- INF/PUC-Rio, acessado em novembro 1, 2025, [https://www.inf.puc-rio.br/\~inf1018/2009.2/interrupcoes.html](https://www.inf.puc-rio.br/~inf1018/2009.2/interrupcoes.html)  
10. Mecanismo de Interrupção \- UFES, acessado em novembro 1, 2025, [https://inf.ufes.br/\~zegonc/material/Sistemas\_Operacionais/Mecanismo%20de%20Interrupcao%20(new).pdf](https://inf.ufes.br/~zegonc/material/Sistemas_Operacionais/Mecanismo%20de%20Interrupcao%20\(new\).pdf)  
11. Interrupção – Wikipédia, a enciclopédia livre, acessado em novembro 1, 2025, [https://pt.wikipedia.org/wiki/Interrup%C3%A7%C3%A3o](https://pt.wikipedia.org/wiki/Interrup%C3%A7%C3%A3o)  
12. O que é DMA? \[Acesso direto à memória\] \- Tecnoblog, acessado em novembro 1, 2025, [https://tecnoblog.net/responde/o-que-e-dma-acesso-direto-a-memoria/](https://tecnoblog.net/responde/o-que-e-dma-acesso-direto-a-memoria/)  
13. Acesso direto à memória – Wikipédia, a enciclopédia livre, acessado em novembro 1, 2025, [https://pt.wikipedia.org/wiki/Acesso\_direto\_%C3%A0\_mem%C3%B3ria](https://pt.wikipedia.org/wiki/Acesso_direto_%C3%A0_mem%C3%B3ria)  
14. DMA: o que é Direct Memory Access e como funciona? \- Adrenaline, acessado em novembro 1, 2025, [https://www.adrenaline.com.br/artigos/dma-o-que-e-direct-memory-access-e-como-funciona/](https://www.adrenaline.com.br/artigos/dma-o-que-e-direct-memory-access-e-como-funciona/)  
15. Linux kernel Block I/O Layer, acessado em novembro 1, 2025, [https://www.cs.cornell.edu/courses/cs4410/2021fa/assets/material/lecture24\_blk\_layer.pdf](https://www.cs.cornell.edu/courses/cs4410/2021fa/assets/material/lecture24_blk_layer.pdf)  
16. The block I/O layer I/O schedulers, acessado em novembro 1, 2025, [https://students.mimuw.edu.pl/ZSO/Wyklady/12\_IOschedulers/IO\_schedulers.pdf](https://students.mimuw.edu.pl/ZSO/Wyklady/12_IOschedulers/IO_schedulers.pdf)  
17. Linux VFS and Block Layers \- Developers Area, acessado em novembro 1, 2025, [https://devarea.com/wp-content/uploads/2017/10/Linux-VFS-and-Block.pdf](https://devarea.com/wp-content/uploads/2017/10/Linux-VFS-and-Block.pdf)  
18. The Virtual File System (VFS) \- UFRJ, acessado em novembro 1, 2025, [https://www.cos.ufrj.br/\~vitor/aulas/COS773/alunos/VFS.pdf](https://www.cos.ufrj.br/~vitor/aulas/COS773/alunos/VFS.pdf)  
19. Multi-Queue Block IO Queueing Mechanism (blk-mq) \- The Linux Kernel Archives, acessado em novembro 1, 2025, [https://www.kernel.org/doc/html//v5.9/block/blk-mq.html](https://www.kernel.org/doc/html//v5.9/block/blk-mq.html)  
20. Multi-Queue Block IO Queueing Mechanism (blk-mq) — The Linux ..., acessado em novembro 1, 2025, [https://docs.kernel.org/block/blk-mq.html](https://docs.kernel.org/block/blk-mq.html)  
21. Linux Multi-Queue Block IO Queueing Mechanism (blk-mq) Details \- Thomas-Krenn-Wiki-en, acessado em novembro 1, 2025, [https://www.thomas-krenn.com/en/wiki/Linux\_Multi-Queue\_Block\_IO\_Queueing\_Mechanism\_(blk-mq)\_Details](https://www.thomas-krenn.com/en/wiki/Linux_Multi-Queue_Block_IO_Queueing_Mechanism_\(blk-mq\)_Details)  
22. Linux Multi-Queue Block IO Queueing Mechanism (blk-mq), acessado em novembro 1, 2025, [https://docs.slackware.com/howtos:hardware:enable\_linux\_multi-queue\_block\_io\_queueing\_mechanism\_blk-mq](https://docs.slackware.com/howtos:hardware:enable_linux_multi-queue_block_io_queueing_mechanism_blk-mq)  
23. Linux Block IO: Introducing Multi-queue SSD Access on Multi-core Systems \- kernel.dk, acessado em novembro 1, 2025, [https://kernel.dk/systor13-final18.pdf](https://kernel.dk/systor13-final18.pdf)  
24. 1\. Overview Guide — GPUDirect Storage Overview Guide, acessado em novembro 1, 2025, [https://docs.nvidia.com/gpudirect-storage/overview-guide/index.html](https://docs.nvidia.com/gpudirect-storage/overview-guide/index.html)  
25. Overview of the Windows I/O Model \- Windows drivers | Microsoft ..., acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/overview-of-the-windows-i-o-model](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/overview-of-the-windows-i-o-model)  
26. The Windows Concept Journey — I/O Manager (Input/Output Manager) | by Shlomi Boutnaru, Ph.D. | Medium, acessado em novembro 1, 2025, [https://medium.com/@boutnaru/the-windows-concept-journey-i-o-manager-input-output-manager-3c14545528ed](https://medium.com/@boutnaru/the-windows-concept-journey-i-o-manager-input-output-manager-3c14545528ed)  
27. Understanding the Windows I/O System | Microsoft Press Store, acessado em novembro 1, 2025, [https://www.microsoftpressstore.com/articles/article.aspx?p=2201309](https://www.microsoftpressstore.com/articles/article.aspx?p=2201309)  
28. I/O request packet \- Wikipedia, acessado em novembro 1, 2025, [https://en.wikipedia.org/wiki/I/O\_request\_packet](https://en.wikipedia.org/wiki/I/O_request_packet)  
29. Packet-Driven I/O with Reusable IRPs \- Windows drivers \- Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/packet-driven-i-o-with-reusable-irps](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/packet-driven-i-o-with-reusable-irps)  
30. Understanding the Windows I/O System | Microsoft Press Store, acessado em novembro 1, 2025, [https://www.microsoftpressstore.com/articles/article.aspx?p=2201309\&seqNum=3](https://www.microsoftpressstore.com/articles/article.aspx?p=2201309&seqNum=3)  
31. I/O Request Packets \- Windows drivers | Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/i-o-request-packets](https://learn.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/i-o-request-packets)  
32. The Windows Concept Journey — IRP (I/O Request Packet) | by Shlomi Boutnaru, Ph.D., acessado em novembro 1, 2025, [https://medium.com/@boutnaru/the-windows-concept-journey-irp-i-o-request-packet-e4229d35214e](https://medium.com/@boutnaru/the-windows-concept-journey-irp-i-o-request-packet-e4229d35214e)  
33. Driver Stacks \- Windows \- Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/driver-stacks](https://learn.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/driver-stacks)  
34. Hard disk drive performance characteristics \- Wikipedia, acessado em novembro 1, 2025, [https://en.wikipedia.org/wiki/Hard\_disk\_drive\_performance\_characteristics](https://en.wikipedia.org/wiki/Hard_disk_drive_performance_characteristics)  
35. Difference between Seek Time and Rotational Latency in Disk Scheduling \- GeeksforGeeks, acessado em novembro 1, 2025, [https://www.geeksforgeeks.org/operating-systems/difference-between-seek-time-and-rotational-latency-in-disk-scheduling/](https://www.geeksforgeeks.org/operating-systems/difference-between-seek-time-and-rotational-latency-in-disk-scheduling/)  
36. Hard Drive Seek Time: What It Means (And Why It Matters) \- Datarecovery.com, acessado em novembro 1, 2025, [https://datarecovery.com/rd/hard-drive-seek-time/](https://datarecovery.com/rd/hard-drive-seek-time/)  
37. Revisiting HDD Rules of Thumb: 1/3 Is Not (Quite) the Average Seek Distance \- MSST, acessado em novembro 1, 2025, [https://www.msstconference.org/MSST-history/2024/Papers/msst24-1.1.pdf](https://www.msstconference.org/MSST-history/2024/Papers/msst24-1.1.pdf)  
38. DISK SCHEDULING ALGORITHMS, acessado em novembro 1, 2025, [http://www.cs.iit.edu/\~cs561/cs450/disksched/disksched.html](http://www.cs.iit.edu/~cs561/cs450/disksched/disksched.html)  
39. Disk Scheduling MCQ \[Free PDF\] \- Objective Question Answer for Disk Scheduling Quiz \- Download Now\! \- Testbook, acessado em novembro 1, 2025, [https://testbook.com/objective-questions/mcq-on-disk-scheduling--5eea6a1539140f30f369f365](https://testbook.com/objective-questions/mcq-on-disk-scheduling--5eea6a1539140f30f369f365)  
40. \[Solved\] Disk scheduling involves deciding \- Testbook, acessado em novembro 1, 2025, [https://testbook.com/question-answer/disk-scheduling-involves-deciding--628f4d59dae1487ffd6ef1be](https://testbook.com/question-answer/disk-scheduling-involves-deciding--628f4d59dae1487ffd6ef1be)  
41. SCAN Disk Scheduling Algorithm in Operating System | Elevator Algorithm | OS \- YouTube, acessado em novembro 1, 2025, [https://www.youtube.com/watch?v=ZeHZh-4\_C3w](https://www.youtube.com/watch?v=ZeHZh-4_C3w)  
42. C-SCAN – Wikipédia, a enciclopédia livre, acessado em novembro 1, 2025, [https://pt.wikipedia.org/wiki/C-SCAN](https://pt.wikipedia.org/wiki/C-SCAN)  
43. Chapter 18\. Setting the disk scheduler | Managing storage devices ..., acessado em novembro 1, 2025, [https://docs.redhat.com/en/documentation/red\_hat\_enterprise\_linux/8/html/managing\_storage\_devices/setting-the-disk-scheduler\_managing-storage-devices](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/managing_storage_devices/setting-the-disk-scheduler_managing-storage-devices)  
44. Selecting a Linux I/O Scheduler \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/1009577/selecting-a-linux-i-o-scheduler](https://stackoverflow.com/questions/1009577/selecting-a-linux-i-o-scheduler)  
45. What is the suggested I/O scheduler to improve disk performance when using Red Hat Enterprise Linux with virtualization?, acessado em novembro 1, 2025, [https://access.redhat.com/solutions/5427](https://access.redhat.com/solutions/5427)  
46. Chapter 12\. Setting the disk scheduler | Monitoring and managing system status and performance | Red Hat Enterprise Linux, acessado em novembro 1, 2025, [https://docs.redhat.com/en/documentation/red\_hat\_enterprise\_linux/8/html/monitoring\_and\_managing\_system\_status\_and\_performance/setting-the-disk-scheduler\_monitoring-and-managing-system-status-and-performance](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance)  
47. Verifying the Disk I/O Scheduler on Linux 8 and Later Systems \- Oracle Help Center, acessado em novembro 1, 2025, [https://docs.oracle.com/en/database/oracle/oracle-database/19/cwlin/setting-the-disk-io-scheduler-on-linux-8.html](https://docs.oracle.com/en/database/oracle/oracle-database/19/cwlin/setting-the-disk-io-scheduler-on-linux-8.html)  
48. BFQ (Budget Fair Queueing) \- The Linux Kernel documentation, acessado em novembro 1, 2025, [https://docs.kernel.org/block/bfq-iosched.html](https://docs.kernel.org/block/bfq-iosched.html)  
49. Deadline(MQ) scheduler sucks, and I don't understand the hype behind it : r/linux \- Reddit, acessado em novembro 1, 2025, [https://www.reddit.com/r/linux/comments/brljoo/deadlinemq\_scheduler\_sucks\_and\_i\_dont\_understand/](https://www.reddit.com/r/linux/comments/brljoo/deadlinemq_scheduler_sucks_and_i_dont_understand/)  
50. Change Windows Server Disk I/O Scheduler \- Microsoft Q\&A, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/answers/questions/2188138/change-windows-server-disk-i-o-scheduler](https://learn.microsoft.com/en-us/answers/questions/2188138/change-windows-server-disk-i-o-scheduler)  
51. Is the elevator disk scheduling algorithm the same as NCQ? \- Stack Overflow, acessado em novembro 1, 2025, [https://stackoverflow.com/questions/6358044/is-the-elevator-disk-scheduling-algorithm-the-same-as-ncq](https://stackoverflow.com/questions/6358044/is-the-elevator-disk-scheduling-algorithm-the-same-as-ncq)  
52. Estruturas SSD e boas práticas \- WhiteHat, acessado em novembro 1, 2025, [https://whitehat.pt/2020/04/06/estruturas-ssd-e-boas-praticas/](https://whitehat.pt/2020/04/06/estruturas-ssd-e-boas-praticas/)  
53. Mainstream solid-state drives \- IBM, acessado em novembro 1, 2025, [https://www.ibm.com/docs/pt-br/power10/9105-42A?topic=drives-mainstream-solid-state](https://www.ibm.com/docs/pt-br/power10/9105-42A?topic=drives-mainstream-solid-state)  
54. Effects of Garbage Collection and TRIM on SSD Performance \- Ontrack Data Recovery, acessado em novembro 1, 2025, [https://www.ontrack.com/en-us/blog/kingston-guest-blog-post-effects-of-garbage-collection-and-trim-on-ssd-performance](https://www.ontrack.com/en-us/blog/kingston-guest-blog-post-effects-of-garbage-collection-and-trim-on-ssd-performance)  
55. What is Write Amplification? \- The SSD Guy, acessado em novembro 1, 2025, [https://thessdguy.com/what-is-write-amplification/](https://thessdguy.com/what-is-write-amplification/)  
56. Write amplification \- Wikipedia, acessado em novembro 1, 2025, [https://en.wikipedia.org/wiki/Write\_amplification](https://en.wikipedia.org/wiki/Write_amplification)  
57. What Are SSD TRIM and Garbage Collection? | Seagate US, acessado em novembro 1, 2025, [https://www.seagate.com/blog/what-are-ssd-trim-and-garbage-collection/](https://www.seagate.com/blog/what-are-ssd-trim-and-garbage-collection/)  
58. Garbage Collection and TRIM in SSDs Explained \- An SSD Primer, acessado em novembro 1, 2025, [https://www.thessdreview.com/daily-news/latest-buzz/garbage-collection-and-trim-in-ssds-explained-an-ssd-primer/2/](https://www.thessdreview.com/daily-news/latest-buzz/garbage-collection-and-trim-in-ssds-explained-an-ssd-primer/2/)  
59. What is trim and active garbage collection? \- Crucial, acessado em novembro 1, 2025, [https://www.crucial.com/articles/about-ssd/what-is-trim](https://www.crucial.com/articles/about-ssd/what-is-trim)  
60. The Importance of Garbage Collection and TRIM Processes for SSD Performance \- Kingston Technology, acessado em novembro 1, 2025, [https://www.kingston.com/en/blog/pc-performance/ssd-garbage-collection-trim-explained](https://www.kingston.com/en/blog/pc-performance/ssd-garbage-collection-trim-explained)  
61. Is mounting with "discard" needed for TRIM? \- Unix & Linux Stack Exchange, acessado em novembro 1, 2025, [https://unix.stackexchange.com/questions/649964/is-mounting-with-discard-needed-for-trim](https://unix.stackexchange.com/questions/649964/is-mounting-with-discard-needed-for-trim)  
62. How to Install and Configure TRIM in Linux \- Baeldung, acessado em novembro 1, 2025, [https://www.baeldung.com/linux/trim-ssd](https://www.baeldung.com/linux/trim-ssd)  
63. Extend the life of your SSD drive with fstrim \- Opensource.com, acessado em novembro 1, 2025, [https://opensource.com/article/20/2/trim-solid-state-storage-linux](https://opensource.com/article/20/2/trim-solid-state-storage-linux)  
64. Does fstrim and discard do different things or discard just doesn't do anything? \- Reddit, acessado em novembro 1, 2025, [https://www.reddit.com/r/linuxquestions/comments/sw56m0/does\_fstrim\_and\_discard\_do\_different\_things\_or/](https://www.reddit.com/r/linuxquestions/comments/sw56m0/does_fstrim_and_discard_do_different_things_or/)  
65. fstrim \- discard unused blocks on a mounted filesystem \- Ubuntu Manpage, acessado em novembro 1, 2025, [https://manpages.ubuntu.com/manpages/jammy/man8/fstrim.8.html](https://manpages.ubuntu.com/manpages/jammy/man8/fstrim.8.html)  
66. Atualizações e otimização do Windows 11: como deixar o PC mais rápido e estável \- Pplware, acessado em novembro 1, 2025, [https://pplware.sapo.pt/zzpublicidade/atualizacoes-otimizacao-windows-11-pc-mais-rapido-estavel/](https://pplware.sapo.pt/zzpublicidade/atualizacoes-otimizacao-windows-11-pc-mais-rapido-estavel/)  
67. Como Otimizar seu SSD no Windows 10/11 para Máximo Desempenho (Guia), acessado em novembro 1, 2025, [https://fernandopires-informatica.com.br/como-otimizar-ssd-windows-10-11/](https://fernandopires-informatica.com.br/como-otimizar-ssd-windows-10-11/)  
68. Otimizar Unidades do Windows \- Windows 11 VM : r/unRAID \- Reddit, acessado em novembro 1, 2025, [https://www.reddit.com/r/unRAID/comments/1nyfr89/windows\_optimize\_storage\_windows\_11\_vm/?tl=pt-br](https://www.reddit.com/r/unRAID/comments/1nyfr89/windows_optimize_storage_windows_11_vm/?tl=pt-br)  
69. Help me understand what transfer/data protocols (NVMe, AHCI) actually are and how they interact with transfer interfaces (PCIe, SATA) : r/hardware \- Reddit, acessado em novembro 1, 2025, [https://www.reddit.com/r/hardware/comments/8d0ivn/help\_me\_understand\_what\_transferdata\_protocols/](https://www.reddit.com/r/hardware/comments/8d0ivn/help_me_understand_what_transferdata_protocols/)  
70. O que é NVMe? \- IBM, acessado em novembro 1, 2025, [https://www.ibm.com/br-pt/think/topics/nvme](https://www.ibm.com/br-pt/think/topics/nvme)  
71. NVMe (Non-volatile Memory Express), a tecnologia para performance em SSD, acessado em novembro 1, 2025, [https://www.controle.net/faq/nvme-non-volatile-memory-express](https://www.controle.net/faq/nvme-non-volatile-memory-express)  
72. Revolução NVMe: Desvendando o Futuro dos Servidores e ..., acessado em novembro 1, 2025, [https://www.e-recovery.com.br/blog/revolucao-nvme-desvendando-o-futuro-dos-servidores-e-sistemas-de-armazenamento-all-flash/](https://www.e-recovery.com.br/blog/revolucao-nvme-desvendando-o-futuro-dos-servidores-e-sistemas-de-armazenamento-all-flash/)  
73. O que é storage NVMe e quais são suas principais aplicações \- Storcenter, acessado em novembro 1, 2025, [https://www.storcenter.com.br/post/o-que-e-storage-nvme-e-quais-sao-suas-aplicacoes](https://www.storcenter.com.br/post/o-que-e-storage-nvme-e-quais-sao-suas-aplicacoes)  
74. NVMe \- Perguntas frequentes gerais \- Azure Virtual Machines | Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/pt-pt/azure/virtual-machines/enable-nvme-faqs](https://learn.microsoft.com/pt-pt/azure/virtual-machines/enable-nvme-faqs)  
75. Red Hat Enterprise Linux: Disk I/O Scheduler | Consolidated Best Practices, acessado em novembro 1, 2025, [https://infohub.delltechnologies.com/en-au/l/consolidated-best-practices-2/red-hat-enterprise-linux-disk-i-o-scheduler/](https://infohub.delltechnologies.com/en-au/l/consolidated-best-practices-2/red-hat-enterprise-linux-disk-i-o-scheduler/)  
76. Which NVMe Drivers are the best (performance related)? \- \#276 by Fernando, acessado em novembro 1, 2025, [https://winraid.level1techs.com/t/which-nvme-drivers-are-the-best-performance-related/32785/276](https://winraid.level1techs.com/t/which-nvme-drivers-are-the-best-performance-related/32785/276)  
77. NVMe | Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/windows-hardware/design/component-guidelines/power-management-for-storage-hardware-devices-nvme](https://learn.microsoft.com/en-us/windows-hardware/design/component-guidelines/power-management-for-storage-hardware-devices-nvme)  
78. Linux NVMe-oF Initiator vs StarWind NVMe-oF Initiator Comparison, acessado em novembro 1, 2025, [https://www.starwindsoftware.com/blog/linux-nvme-of-initiator-and-starwind-nvme-of-initiator-for-windows-performance-comparison-part-2-1/](https://www.starwindsoftware.com/blog/linux-nvme-of-initiator-and-starwind-nvme-of-initiator-for-windows-performance-comparison-part-2-1/)  
79. NVMe SSD speeds crippled in Win 11 \-- Neowin site has the details ..., acessado em novembro 1, 2025, [https://www.reddit.com/r/Windows11/comments/razyzf/nvme\_ssd\_speeds\_crippled\_in\_win\_11\_neowin\_site/](https://www.reddit.com/r/Windows11/comments/razyzf/nvme_ssd_speeds_crippled_in_win_11_neowin_site/)  
80. Western Digital NVMe SSD users beware: Windows 11 24H2 is ..., acessado em novembro 1, 2025, [https://www.reddit.com/r/hardware/comments/1g4ccbu/western\_digital\_nvme\_ssd\_users\_beware\_windows\_11/](https://www.reddit.com/r/hardware/comments/1g4ccbu/western_digital_nvme_ssd_users_beware_windows_11/)  
81. Troubleshoot Operating System Disk Sector Size Greater Than 4 KB \- SQL Server | Microsoft Learn, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/troubleshoot/sql/database-engine/database-file-operations/troubleshoot-os-4kb-disk-sector-size](https://learn.microsoft.com/en-us/troubleshoot/sql/database-engine/database-file-operations/troubleshoot-os-4kb-disk-sector-size)  
82. AMD Ryzen AI 5 340 Windows 11 vs. Ubuntu Linux Performance For Budget "Krackan Point" Laptops \- Phoronix, acessado em novembro 1, 2025, [https://www.phoronix.com/review/amd-krackan-point-windows-linux/6](https://www.phoronix.com/review/amd-krackan-point-windows-linux/6)  
83. Windows 11 vs. Linux Performance For Intel Core i9 12900K In Mid-2022 \- Phoronix Forums, acessado em novembro 1, 2025, [https://www.phoronix.com/forums/forum/software/distributions/1333450-windows-11-vs-linux-performance-for-intel-core-i9-12900k-in-mid-2022](https://www.phoronix.com/forums/forum/software/distributions/1333450-windows-11-vs-linux-performance-for-intel-core-i9-12900k-in-mid-2022)  
84. The Performance Cost To Ubuntu WSL2 On Windows 11 25H2 \- Phoronix, acessado em novembro 1, 2025, [https://www.phoronix.com/review/windows-11-wsl2-2025/6](https://www.phoronix.com/review/windows-11-wsl2-2025/6)  
85. O que é armazenamento SSD NVMe? \- YouTube, acessado em novembro 1, 2025, [https://www.youtube.com/watch?v=haLhfwfD9Do](https://www.youtube.com/watch?v=haLhfwfD9Do)  
86. Load PC Games Faster: How to Use DirectStorage in Windows 11 \- PCMag Australia, acessado em novembro 1, 2025, [https://au.pcmag.com/pc-games/101317/load-pc-games-faster-how-to-use-directstorage-in-windows-11](https://au.pcmag.com/pc-games/101317/load-pc-games-faster-how-to-use-directstorage-in-windows-11)  
87. DirectStorage libera até 40% do uso do CPU de acordo com Microsoft \- Adrenaline, acessado em novembro 1, 2025, [https://www.adrenaline.com.br/games/pc-games/directstorage-libera-ate-40-do-uso-do-cpu-de-acordo-com-microsoft/](https://www.adrenaline.com.br/games/pc-games/directstorage-libera-ate-40-do-uso-do-cpu-de-acordo-com-microsoft/)  
88. O que é Microsoft DirectStorage e como isso melhora os jogos no ..., acessado em novembro 1, 2025, [https://www.kingston.com/br/blog/gaming/microsoft-directstorage-pc-gaming](https://www.kingston.com/br/blog/gaming/microsoft-directstorage-pc-gaming)  
89. DirectStorage Overview \- Microsoft Game Development Kit, acessado em novembro 1, 2025, [https://learn.microsoft.com/en-us/gaming/gdk/docs/features/console/storage/directstorage/directstorage-overview](https://learn.microsoft.com/en-us/gaming/gdk/docs/features/console/storage/directstorage/directstorage-overview)  
90. How to use DirectStorage in Windows 11 \- IONOS, acessado em novembro 1, 2025, [https://www.ionos.com/digitalguide/server/configuration/directstorage/](https://www.ionos.com/digitalguide/server/configuration/directstorage/)  
91. DirectStorage: API reduz o uso de CPU em até 40% no Windows 11, diz Microsoft, acessado em novembro 1, 2025, [https://www.tudocelular.com/software/noticias/n188006/directstorage-uso-cpu-ate-40-windows-11-microsoft.html](https://www.tudocelular.com/software/noticias/n188006/directstorage-uso-cpu-ate-40-windows-11-microsoft.html)  
92. BypassIO em Drivers de Armazenamento \- Windows drivers, acessado em novembro 1, 2025, [https://learn.microsoft.com/pt-br/windows-hardware/drivers/storage/bypassio](https://learn.microsoft.com/pt-br/windows-hardware/drivers/storage/bypassio)  
93. With games starting to use DirectStorage, Does Linux have an alternative yet? \- Reddit, acessado em novembro 1, 2025, [https://www.reddit.com/r/linux\_gaming/comments/y3rm2a/with\_games\_starting\_to\_use\_directstorage\_does/](https://www.reddit.com/r/linux_gaming/comments/y3rm2a/with_games_starting_to_use_directstorage_does/)  
94. So direct storage does not work on linux? : r/linux\_gaming \- Reddit, acessado em novembro 1, 2025, [https://www.reddit.com/r/linux\_gaming/comments/1jymu15/so\_direct\_storage\_does\_not\_work\_on\_linux/](https://www.reddit.com/r/linux_gaming/comments/1jymu15/so_direct_storage_does_not_work_on_linux/)  
95. One thing I'm curious about is the RTX IO feature. The slide said it supports ... | Hacker News, acessado em novembro 1, 2025, [https://news.ycombinator.com/item?id=24347607](https://news.ycombinator.com/item?id=24347607)  
96. io\_uring: Linux Performance Boost or Security Headache? \- Upwind, acessado em novembro 1, 2025, [https://www.upwind.io/feed/io\_uring-linux-performance-boost-or-security-headache](https://www.upwind.io/feed/io_uring-linux-performance-boost-or-security-headache)  
97. The same Windows NT whose decades-old async IO capabilities are so good they imm, acessado em novembro 1, 2025, [https://news.ycombinator.com/item?id=41472061](https://news.ycombinator.com/item?id=41472061)  
98. Clearing up misconceptions about DirectStorage : r/pcgaming \- Reddit, acessado em novembro 1, 2025, [https://www.reddit.com/r/pcgaming/comments/tleiwb/clearing\_up\_misconceptions\_about\_directstorage/](https://www.reddit.com/r/pcgaming/comments/tleiwb/clearing_up_misconceptions_about_directstorage/)  
99. From epoll to io\_uring's Multishot Receives — Why 2025 Is the Year We Finally Kill the Event Loop \- Codemia, acessado em novembro 1, 2025, [https://codemia.io/blog/path/From-epoll-to-iourings-Multishot-Receives--Why-2025-Is-the-Year-We-Finally-Kill-the-Event-Loop](https://codemia.io/blog/path/From-epoll-to-iourings-Multishot-Receives--Why-2025-Is-the-Year-We-Finally-Kill-the-Event-Loop)  
100. From epoll to io\_uring's Multishot Receives — Why 2025 Is the Year We Finally Kill the Event Loop : r/programming \- Reddit, acessado em novembro 1, 2025, [https://www.reddit.com/r/programming/comments/1mqfp7c/from\_epoll\_to\_io\_urings\_multishot\_receives\_why/](https://www.reddit.com/r/programming/comments/1mqfp7c/from_epoll_to_io_urings_multishot_receives_why/)