# Apresentação

::: {.callout-note}
**Este livro ainda está em desenvolvimento. A versão atual é um rascunho inicial, e muitas seções ainda estão sendo escritas. Agradecemos por sua paciência e compreensão enquanto  trabalhamos para criar um conteúdo de alta qualidade.**

Muito bem-vinda, audaciosa leitora!

Lembre-se de que este livro também é um dos materiais de apoio da disciplina de Sistemas Computacionais do curso de Engenharia de Computação da Pontifícia Universidade Católica do Paraná. 

**Um dos materiais de apoio!** Não é o único, nem o melhor. Isso significa que a atenta leitora não deve se limitar a este material. Consulte, por exemplo, os livros sugeridos na Bibliografia da disciplina, listada no plano de ensino. Os livros sugeridos nesta bibliografia estão disponíveis nas bibliotecas do Campus Curitiba. Este livros são: 

**Bibliografia Básica**:

1.	TANENBAUM, Andrew S.; BOS, Herbert. **Sistemas Operacionais Modernos**. 4ª ed. São Paulo: Pearson, 2016.
2.	SILBERSCHATZ, Abraham; GALVIN, Peter B.; GAGNE, Greg. **Sistemas Operacionais: Conceitos e Aplicações**. 9ª ed. Rio de Janeiro: LTC, 2015.
3.	STALLINGS, William. **Arquitetura e Organização de Computadores**. 10ª ed. São Paulo: Pearson, 2017.

**Bibliografia Complementar**:

1. LOVE, Robert. **Linux Kernel Development**. 3ª ed. Addison-Wesley Professional, 2010.
2. ARPACI-DUSSEAU, Remzi H.; ARPACI-DUSSEAU, Andrea C. **Operating Systems: Three Easy Pieces**. Arpaci-Dusseau Books, 2018.
3. BURNS, Brendan; BEDA, Joe; HIGHTOWER, Kelsey. **Kubernetes: Up and Running**. 2ª ed. O'Reilly Media, 2019.
4. MOUAT, Adrian. **Using Docker: Developing and Deploying Software with Containers**. O'Reilly Media, 2015.
5. KLEPPMANN, Martin. **Designing Data-Intensive Applications**. O'Reilly Media, 2017.
6. BOVET, Daniel P.; CESATI, Marco. **Understanding the Linux Kernel**. 3ª ed. O'Reilly Media, 2005.

Além disso, observe que o texto está sendo escrito visando a publicação. Ou seja, existem seções que só serão revisadas, escritas e finalizadas ao longo da disciplina. Portanto, não se surpreenda se encontrar erros de digitação, gramática ou mesmo de conteúdo. Agradeço caso possa indicar possíveis correções e melhorias.

Um indício importante é a existência de um arquivo `expresso` para um determinado capítulo. A existência do `expresso` indica que o capítulo foi revisado pelo menos uma vez. Se não houver o `expresso`, é porque o capítulo ainda está em fase de escrita e revisão.
:::

Este livro é o resultado de uma longa jornada pelo fascinante mundo dos **Sistemas Operacionais**. O objetivo é fornecer uma base sólida, desde os conceitos históricos até as fronteiras mais modernas da tecnologia. Abordaremos tópicos essenciais como gerenciamento de processos, memória, sistemas de arquivos e concorrência, em uma jornada audaciosa aos confins de um dos sistemas mais complexos criados pelo ser humano.

Aqui, vamos usar o C++23 para desenvolver todos os nossos exemplos, testes e códigos de demonstração e simulação. O C++ é uma linguagem de programação poderosa e versátil, amplamente utilizada no desenvolvimento de **Sistemas Operacionais**, software de alto desempenho e aplicações críticas. Sua sintaxe rica e recursos avançados, como gerenciamento de memória manual, permitem um controle preciso sobre o hardware, tornando-o ideal para explorar os conceitos fundamentais de **Sistemas Operacionais**. A precavida leitora precisará dos conhecimentos básicos de C++. É preferível que esteja ciente das novas técnicas e artefatos implementados na linguagem a partir do C++20 e que seja capaz de criar e rodar programas, tanto no Windows quanto no Ubuntu/Linux. Vamos usar preferencialmente o C++23. Logo, caberá à audaciosa leitora criar e manter seu próprio ambiente de desenvolvimento.

Não se deixe impressionar com o uso do C++23, pois encontrará textos em Assembly de vez ou outra. Além disso, a leitora precisará de algum conhecimento básico de computação, como saber o que é um MegaByte, um disco rígido ou um `_cache_`.

Muito será escrito, muito será testado e a jornada será árdua, longa e para poucos. Mas por enquanto, isso tudo é só pretensão. Ainda estamos na fase de pesquisa, redação e design. 

Muito há por vir. Afinal, de que vale sonhar pequeno?
